# ---- Datasource MySQL (desarrollo) ----
spring.datasource.url=jdbc:mysql://${MYSQL_DEV_URL}?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQL_DEV_USERNAME}
spring.datasource.password=${MYSQL_DEV_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway — habilitado en desarrollo para iterar migraciones
spring.flyway.enabled=true

# Logging SQL en desarrollo
logging.level.org.hibernate.SQL=DEBUG
